feat: typeOrm config & migrations & entities
f-lab-edu/Bidders pull request #7
Opened 2023-11-20 14:10 UTC by bitkunst

1. TypeOrm 설정 작업
2. migrations 만들기 (generate, run, revert, create)
3. entities 만들기

2023-11-20 16:49 UTC, f-lab-elkein commented
> < 질문 >
> 
> 1. 애플리케이션에서 엔티티를 공유할 목적으로 libs디렉토리에 엔티티 생성,, 맞는 방향성인지 궁금합니다.
> 2. .env 파일을 루티 디렉토리에 만들고 isGlobal true 옵션으로 사용 중인데,, 만약 apps 디렉토리 안에 여러개의 애플리케이션이 존재한다면 .env 파일은 루트 디렉토리가 아니라 apps 안에 있는 애플리케이션 별로 각각 존재해야 하지 않는가에 대한 궁금증이 있습니다.
> 3. TypeOrm에서 entity 간의 관계 설정에서 @manytoone() 과 @OnetoOne()의 대상이 되는 엔티티에만 @JoinColum()을 명시했는데,, 해당 사항은 아무런 이슈가 없는지 궁금합니다.

답변 먼저 드리고 상세한 코드 리뷰는 낮에 진행할게요.

1. 네 공유 목적으로 사용해도 됩니다만, DTO가 아닌 엔티티를 공유하실 건가요? DTO는 적합한데, 엔티티는 어떠한 장단점이 있는지 나열하고, 명확한 결정으로 해주시면 좋겠습니다.
2. .env 파일은 말씀하신대로 각 app 안에 있어야 합니다.
3. 이 부분은 내일 답변 드릴게요.

2023-11-21 04:32 UTC, f-lab-elkein commented
몇가지 테스트를 해보고 피드백 드리려했는데, 궁금증이 있습니다.

현재 폴더 지정 경로 등의 이슈로 마이그레이션이 안되는거 같은데, 혹시 어떠한 방식으로 마이그레이션 하시나요?

추가적으로, mysql-typeorm-config.service.ts와 mysql-typeorm.config.ts 를 나누신 의도가 궁금합니다.

2023-11-21 04:33 UTC, f-lab-elkein commented
테스트할 API에 대한 규격이 버전 관리에 포함되면 좋겠습니다.

https://github.com/Huachao/vscode-restclient

위 플러그인 규격으로 사용 가능한 .http 파일을 특정 폴더에 올려주시면 감사하겠습니다.

2023-11-21 04:44 UTC, bitkunst commented
현재 .env 파일은 루트 디렉토리 상에 위치해있는 상태이고, 마이그레이션 명령어는 package.json 파일 안에 스크립트로 만들어서 진행했습니다. 
mysql-migrations 디렉 안에 마이그레이션 파일 올려놓은 상태라서, $ npm run migration:run 명령어로 마이그레이션 진행하시면 될 것 같습니다. 

mysql-typeorm-config.service.ts와 mysql-typeorm.config.ts 를 나누신 의도가 궁금합니다.
-> config.ts 파일은 dataSource만을 가져와서 스크립트 명령어로 마이그레이션 진행하기 위함 (실제 --dataSource 옵션으로 마이그레이션 진행하고 있습니다.) + 관계성이 잘 맺어졌는지 확인해보기 위해 엔티티 관련 테스트 코드를 몇개 작성했는데 마찬가지로 그 때 dataSource만 가져와서 작업하기 위한 용도로 따로 만들었습니다.

위 플러그인 규격으로 사용 가능한 .http 파일을 특정 폴더에 올려주시면 감사하겠습니다.
-> 넵! 아직 API를 만들기 전이라,, 향후 만들 것들은 http 파일에 작성해서 올리도록 하겠습니다ㅎㅎ

2023-11-21 04:53 UTC, f-lab-elkein commented
코드 리뷰는 같이 일하는 동료라는 가정하에 진행하는 것이기 때문에, 어떠한 작업에 대한 설명을 README 등에 작성해주셔야 합니다.

또한 패키지 매니저도 여럿이 있는데, 이 중 npm을 썼다면 npm, pnpm, yarn 등 여러 매니저 중 왜 npm 인가도 설명해주시면 좋습니다.

2023-11-21 04:59 UTC, bitkunst commented
넵! 알겠습니다. README 업데이트 진행하겠습니다.

2023-11-21 05:02 UTC, f-lab-elkein commented
> 넵! 알겠습니다. README 업데이트 진행하겠습니다.

테스트에 대한 설명, 사용한 패키지에 대한 설명, 각 커맨드를 손쉽게 따라하는 가이드, 각 커맨드의 의미까지 자세히 적어주실 수록 좋습니다

2023-11-21 05:13 UTC, f-lab-elkein requested changes

2023-11-21 05:13 UTC, f-lab-elkein commented on libs/entity/src/auction-item/auction-item.entity.ts
> +import {
Nest can't resolve dependencies of the AppService (?). Please make sure that the argument ConfigService at index [0] is available in the RootTestModule context.     

jest 테스트를 돌리면 위 메시지와 함께 실패가 나네요

2023-11-21 05:13 UTC, f-lab-elkein commented on libs/entity/src/auction-item/auction-item.entity.ts
> +    Entity,
이외에도 test가 검증하고자 하는 요소 설명과 기준이 있으면 좋겠습니다. (코드 내 주석이어도 괜찮습니다)

2023-11-21 05:24 UTC, bitkunst commented on libs/entity/src/auction-item/auction-item.entity.ts
> +import {
프로젝트 생성시 자동으로 만들어진 app.controller.spec.ts 파일에서 에러가 나는 것 같습니다. 제가 기존에 작성되어 있던 app.controller.ts 파일의 return 값을 수정해 버려서,,, 
수정하겠습니다!

2023-11-21 05:28 UTC, bitkunst commented on libs/entity/src/auction-item/auction-item.entity.ts
> +    Entity,
제가 아직 테스트 코드 작성이 많이 미숙해서,, 기준에 대한 부분이 명확하지 못한 것 같습니다.ㅠㅠ
주석과 함께 수정해보겠습니다!

2023-11-21 11:04 UTC, bitkunst commented
README 업데이트 했고, 테스트 코드 작성시 어떤 테스트들인지 명시적으로 보이게끔 수정했습니다!

2023-11-21 13:50 UTC, f-lab-elkein commented
> < 질문 >
> 
> 1. 애플리케이션에서 엔티티를 공유할 목적으로 libs디렉토리에 엔티티 생성,, 맞는 방향성인지 궁금합니다.
> 2. .env 파일을 루티 디렉토리에 만들고 isGlobal true 옵션으로 사용 중인데,, 만약 apps 디렉토리 안에 여러개의 애플리케이션이 존재한다면 .env 파일은 루트 디렉토리가 아니라 apps 안에 있는 애플리케이션 별로 각각 존재해야 하지 않는가에 대한 궁금증이 있습니다.
> 3. TypeOrm에서 entity 간의 관계 설정에서 ManyToOne 과 OneToOne의 대상이 되는 엔티티에만 @JoinColum()을 명시했는데,, 해당 사항은 아무런 이슈가 없는지 궁금합니다.

3. 이슈 없는 것으로 인지하고 있는데, 저도 잘못 알고 있을 수 있어서, 기능을 더 붙여가면서 다시 체크해보시죠

2023-11-21 13:50 UTC, f-lab-elkein approved these changes
👍 수고하셨습니다.

2023-11-22 00:16 UTC, merged